Fix SuperLUDist lib name, require PETSC and TRILINOS install dirs (#2)
I have updated these scripts to work with the current version of PETSc
'master' that pulls SuperLUDist from the GitHub repo and uses tag v5.0.0.

I also updated the scripts to require that the env vars PETSC_INSTALL_DIR and
TRILINOS_INSTALL_DIR be explicitly set by the user and not assumed.  This
tripped my up the first time I tried to do static lib build and it found the
wrong install dir first try.

diff --git a/scripts/do-configure-fissile4 b/scripts/do-configure-fissile4
--- a/scripts/do-configure-fissile4
+++ b/scripts/do-configure-fissile4
@@ -44,13 +44,10 @@
 #   $ mkdir <some-other-build-dir>
 #   $ cd <some-other-build-dir>/
 #   $ ln -s <this-script> do-configure
-#   $ export TRILINOS_DIR=<trilinos-src-dir>
 #   $ ./do-configure
 #   $ make -j12
 #   $ ctest -j12
 #
-# NOTE: TRILINOS_DIR is just neeed to find the dev env on the Fissile4
-# mahcines.
 
 _ABS_FILE_PATH=`readlink -f $0`
 _SCRIPT_DIR=`dirname $_ABS_FILE_PATH`
@@ -66,15 +63,18 @@ if [ "$TRILINOS_DIR" == "" ] ; then
 fi
 TRILINOS_DIR_ABS=$(readlink -f $TRILINOS_DIR)
 echo "TRILINOS_DIR_ABS = $TRILINOS_DIR_ABS"
+# NOTE: TRILINOS_DIR is only needed for the Dev Env on the Fissile4 machines.
 
 if [ "$TRILINOS_INSTALL_DIR" == "" ] ; then
-  TRILINOS_INSTALL_DIR=/home/8vt/localhome/PROJECTS/Trilinos.base/install/mpi_debug_debug
+  echo "Error, must set env var TRILINOS_INSTALL_DIR!"
+  exit 1
 fi
 TRILINOS_INSTALL_DIR_ABS=$(readlink -f $TRILINOS_INSTALL_DIR)
 echo "TRILINOS_INSTALL_DIR_ABS = $TRILINOS_INSTALL_DIR_ABS"
 
 if [ "$PETSC_INSTALL_DIR" == "" ] ; then
-  PETSC_INSTALL_DIR=/home/8vt/localhome/PROJECTS/PETSc.base/install/mpi-debug
+  echo "Error, must set env var PETSC_INSTALL_DIR!"
+  exit 1
 fi
 echo "PETSC_INSTALL_DIR = $PETSC_INSTALL_DIR"
 
diff --git a/scripts/do-configure-trilinos-fissile4 b/scripts/do-configure-trilinos-fissile4
--- a/scripts/do-configure-trilinos-fissile4
+++ b/scripts/do-configure-trilinos-fissile4
@@ -51,7 +51,8 @@ TRILINOS_DIR_ABS=$(readlink -f $TRILINOS_DIR)
 echo "TRILINOS_DIR_ABS = $TRILINOS_DIR_ABS"
 
 if [ "$PETSC_INSTALL_DIR" == "" ] ; then
-  PETSC_INSTALL_DIR=/home/8vt/localhome/PROJECTS/PETSc.base/install/mpi-debug
+  echo "Error, must set env var PETSC_INSTALL_DIR!"
+  exit 1
 fi
 
 DRIVERS_BASE_DIR=$TRILINOS_DIR_ABS/cmake/ctest/drivers/fissile4
@@ -71,7 +72,7 @@ cmake \
   -D ParMETIS_INCLUDE_DIRS="${PETSC_INSTALL_DIR}/include" \
 -D TPL_ENABLE_SuperLUDist=ON \
   -D SuperLUDist_LIBRARY_DIRS="${PETSC_INSTALL_DIR}/lib" \
-  -D SuperLUDist_LIBRARY_NAMES="superlu_dist_4.1" \
+  -D SuperLUDist_LIBRARY_NAMES="superlu_dist" \
   -D SuperLUDist_INCLUDE_DIRS="${PETSC_INSTALL_DIR}/include" \
 -D TPL_ENABLE_HYPRE=ON \
   -D HYPRE_LIBRARY_DIRS="${PETSC_INSTALL_DIR}/lib" \
